### ISSUE TITLE
Rem to px

### ISSUE THREAD

**Issue by JuanPabloOS** [jinpill/spotlight-in-vscode#1]
Hi, I love what you are doing here.

Do you have any plans to add a rem2px functionality?

**Comment by jinpill** [comment]
I apologize for the delay in responding, but here's my answer now.
Thank you for bringing up the idea of the rem2px functionality.
I appreciate your suggestion, and I believe I will be able to incorporate it soon. 👍

**Comment by jinpill** [comment]
I have added the rem2px functionality.
To use this feature, please append "**to px**" or "**topx**" at the end of the value. (For example, 1.5 topx)
Thank you!
